# Generated by Django 4.2.1 on 2023-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipesName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('recipesDifficult', models.CharField(max_length=30)),
            ],
        ),
    ]
