# Generated by Django 4.2.1 on 2023-06-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipesName', models.CharField(max_length=30)),
                ('recipesDifficult', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('favorite', models.ManyToManyField(related_name='favorite_recipe', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
