# Generated by Django 4.2.1 on 2023-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(null=True, upload_to='recipe_images/'),
        ),
    ]
