# Generated by Django 4.2.1 on 2023-06-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_category_recipe_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('nameCategory', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.category'),
        ),
    ]
