# Generated by Django 4.2.1 on 2023-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_image_recipe_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
